version: "3"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - .data:/data
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet:
